### ISSUE TITLE
yarn create @neutrionjs/react <directory> fails with unexpected error

### ISSUE THREAD

**Issue by mkalakota** [mozilla-neutrino/neutrino-dev#1007]
### yarn create @neutrinojs/react <directory> fails with unexpected error

```
yarn create v1.9.2
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@neutrinojs%2fcreate-react: Not found".
info If you think this is a bug, please open a bug report with the information provided in "yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

contents of yarn-error.log
```log
Yarn version: 
  1.9.2

Node version: 
  8.11.3

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@neutrinojs%2fcreate-react: Not found
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\cli.js:64150:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\lib\cli.js:137416:22)
      at emitTwo (events.js:126:13)
      at Request.emit (events.js:214:7)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:138388:10)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:138310:12)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:111:20)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```

**Comment by mkalakota** [comment]
Sorry, it's my spelling error

I typed `neutrion` instead 'neutrino`

Apologies
