### ISSUE TITLE
The provided value is not an absolute path! - error

### ISSUE THREAD

**Issue by pekkah** [mozilla-neutrino/neutrino-dev#136]
Getting this error when running neutrino build:

```
$ neutrino build
{ WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "c:\\projects\\ProjectIdentity\\src\\Identity" is not an absolute path!

 - configuration.output.path: The provided value "c:\\projects\\ProjectIdentity\\src\\Identity\\build" is not an absolute path!

    at webpack (c:\projects\ProjectIdentity\src\Identity\node_modules\webpack\lib\webpack.js:19:9)
    at Promise (c:\projects\ProjectIdentity\src\Identity\node_modules\neutrino\src\neutrino.js:130:23)
    at Neutrino.builder (c:\projects\ProjectIdentity\src\Identity\node_modules\neutrino\src\neutrino.js:128:11)
    at emitForAll.then (c:\projects\ProjectIdentity\src\Identity\node_modules\neutrino\src\neutrino.js:62:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
  name: 'WebpackOptionsValidationError',
  message: 'Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.\n - configuration.context: The provided value "c:\\\\projects\\\\ProjectIdentity\\\\src\\\\Identity" is not an absolute path!\n\n - configuration.output.path: The provided value "c:\\\\projects\\\\ProjectIdentity\\\\src\\\\Identity\\\\build" is not an absolute path!\n',
  validationErrors:
   [ { keyword: 'absolutePath',
       params: [Object],
       message: 'The provided value "c:\\\\projects\\\\ProjectIdentity\\\\src\\\\Identity" is not an absolute path!\n',
       parentSchema: [Object],
       dataPath: '.context',
       schemaPath: '#/properties/context/absolutePath',
       schema: true,
       data: 'c:\\projects\\ProjectIdentity\\src\\Identity' },
     { keyword: 'absolutePath',
       params: [Object],
       message: 'The provided value "c:\\\\projects\\\\ProjectIdentity\\\\src\\\\Identity\\\\build" is not an absolute path!\n',
       parentSchema: [Object],
       dataPath: '.output.path',
       schemaPath: '#/definitions/output/properties/path/absolutePath',
       schema: true,
       data: 'c:\\projects\\ProjectIdentity\\src\\Identity\\build' } ] }
```

- Tried overriding the output.path with a custom preset, but no luck
- Tried upgrading to 5.0.0-* but no change

**Comment by pekkah** [comment]
Seems to be caused by this https://github.com/webpack/webpack/issues/4530

**Comment by eliperelman** [comment]
According to https://github.com/webpack/webpack/issues/4530#issuecomment-289446592 it appears this is fixed in latest webpack.

**Comment by pekkah** [comment]
This was fixed in webpack

**Comment by hcarreras** [comment]
In case someone stumbles upon this while googling a similar issue. I was following an old tutorial which had a webpack.config.js older that 2.x
I solved it by adding the context to the path:

In my case, this was the working example: 

```
const webpack = require('webpack');
const path = require('path');

module.exports = {
  context: __dirname,
  entry: './app/src/index.js',
  output: {
    path: __dirname + '/app/build',
    filename: 'bundle.js',
    publicPath: '/'
  },
  devtool: 'eval-source-map',
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    })
  ]
}
```

**Comment by rakeshIngenuity** [comment]
thanks @hcarreras
its working after adding context
