### ISSUE TITLE
Remove/disable a used preset

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#168]
Basically I want to extend `neutrino-preset-web`, but want to exclude `neutrino.use(htmlTemplate, neutrino.options.html)` (neutrino-middleware-html-template) in favor of a serverside proxy configuration.

Do I need to just have my own fork of `neutrino-preset-web`, or is there a way to use it and remove the neutrino-middleware-html-template part?

**Comment by timkelty** [comment]
This seems to work:

```
  neutrino.use(web);
  neutrino.config
    .plugins.delete('html').end()
    .plugin('manifest')
      .use(ManifestPlugin)
      .end();
```

**Comment by eliperelman** [comment]
You are correct! To remove the plugin that the middleware uses, what you have is right. Then you can just add whatever other configuration you desire.

If you find that you use this modification regularly, you can make it into your own middleware.

**Comment by timkelty** [comment]
Thank you!

**Comment by trusktr** [comment]
@eliperelman This doesn't seem to always work. For example, disabling the `hot` plugin from the `node` preset causes an error.

I have this `.neutrinorc.js` file:

```js
module.exports = {
  use: [
    'neutrino-preset-node',

    // disable Hot Module Reloading for now, it's buggy.
    n => {
      return n
        .config
        .plugins
        .delete('hot')
    },

  ],
  options: {
    entry: 'server/index',
  },
}
```

and running `neutrino start` causes this error:

```
✔ Build completed
/path/to/project/build/index.js:739
        throw new Error("[HMR] Hot Module Replacement is disabled.");
        ^

Error: [HMR] Hot Module Replacement is disabled.
    at Object.<anonymous> (/path/to/project/build/index.js:739:8)
    at __webpack_require__ (/path/to/project/build/index.js:21:30)
    at Object.<anonymous> (/path/to/project/build/index.js:1068:18)
    at __webpack_require__ (/path/to/project/build/index.js:21:30)
    at /path/to/project/build/index.js:67:18
    at Object.<anonymous> (/path/to/project/build/index.js:70:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
