### ISSUE TITLE
Npm start failed to launch the project !

### ISSUE THREAD

**Issue by alamenai** [mozilla-neutrino/neutrino-dev#1706]
#### Run this command :
```
❯ npx @neutrinojs/create-project <directory-name>
```
#### Next command : 
```
npm start
```
#### Internal Error:

```
 react-app@1.0.0 start
> webpack-dev-server --mode development --open

ℹ ｢wds｣: Project is running at http://localhost:5000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/alaeddine/Apps/react-app
ℹ ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/alaeddine/Apps/react-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/alaeddine/Apps/react-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/alaeddine/Apps/react-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/alaeddine/Apps/react-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/alaeddine/Apps/react-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/alaeddine/Apps/react-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/alaeddine/Apps/react-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/alaeddine/Apps/react-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by zenril** [comment]
same issue using 19.6.0
and using yarn

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358
