### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by lielran** [mozilla-neutrino/neutrino-dev#299]
not sure why the build is failed with this error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.1.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle my-project@1.0.0~prebuild: my-project@1.0.0
6 info lifecycle my-project@1.0.0~build: my-project@1.0.0
7 verbose lifecycle my-project@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle my-project@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/me/projects/cloudbills.io/my-project/node_modules/.bin:/Users/me/.yarn/bin:/Users/me/golang/bin:/Users/me/golang:/usr/local/share/npm/bin:~/Library/Python/2.7/bin:/opt/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/bin:/usr/local/go/bin:/Users/me/.rvm/bin:/Users/me/Library/Android/sdk/tools:/Users/me/Library/Android/sdk/platform-tools
9 verbose lifecycle my-project@1.0.0~build: CWD: /Users/me/projects/cloudbills.io/my-project
10 silly lifecycle my-project@1.0.0~build: Args: [ '-c', 'neutrino build' ]
11 silly lifecycle my-project@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle my-project@1.0.0~build: Failed to exec build script
13 verbose stack Error: my-project@1.0.0 build: `neutrino build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid my-project@1.0.0
15 verbose cwd /Users/me/projects/cloudbills.io/my-project
16 verbose Darwin 16.6.0
17 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.1.3
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-project@1.0.0 build: `neutrino build`
22 error Exit status 1
23 error Failed at the my-project@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I tried to run it with ```npm run build``` and ```yarn build```
working on latest version of neutrino (and neutrino-preset-react)

**Comment by eliperelman** [comment]
Are you still experiencing this issue? If so, could you create a repository which we can use to replicate this? Thanks!

**Comment by eliperelman** [comment]
Closing as inactive. If you still continue to see this issue, please reopen with a test repository. Thanks!
