### ISSUE TITLE
Problems testing React component

### ISSUE THREAD

**Issue by zeropaper** [mozilla-neutrino/neutrino-dev#363]
I am trying to setup tests for a React component with the following dependencies
(npm version is 5.5.1, node is 8.3.0)

```
  "devDependencies": {
    "autoprefixer": "^7.1.5",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "neutrino": "^7.1.1",
    "neutrino-middleware-postcss": "^3.0.0",
    "neutrino-middleware-pwa": "^7.1.1",
    "neutrino-preset-airbnb-base": "^7.1.1",
    "neutrino-preset-jest": "^7.1.3",
    "neutrino-preset-react": "^7.1.1",
    "react-test-renderer": "^16.0.0"
  },
  "dependencies": {
    "moment": "^2.19.1",
    "normalize.css": "^7.0.0",
    "open-sans-fontface": "^1.4.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-hot-loader": "^3.0.0"
  }
```

with the following test file content:

```js
import React from 'react';
import { shallow, mount, render } from 'enzyme';
import Calendar from './../src/components/calendar.jsx';

describe('simple', () => {
  it('should be sane', () => {
    expect(false).not.toBe(true);
  });
});

describe('<Calendar>', () => {
  it('renders 1 <Calendar /> component', () => {
    const wrapper = mount(<Calendar />);
  });
});
```

but get the following error:

```
$ npm test

> x-react-calendar@0.0.1 test .../x-react-calendar
> neutrino test

 FAIL  test/simple_test.js
  simple
    ✓ should be sane (4ms)
  <Calendar>
    ✕ renders 1 <Calendar /> component (2ms)

  ● <Calendar> › renders 1 <Calendar /> component

    
          Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
          configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:
    
          import Adapter from 'enzyme-adapter-react-15';
    
          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html
      
          
      at validateAdapter (.../x-react-calendar/node_modules/enzyme/build/validateAdapter.js:14:11)
      at getAdapter (.../x-react-calendar/node_modules/enzyme/build/Utils.js:71:36)
      at new ReactWrapper (.../x-react-calendar/node_modules/enzyme/build/ReactWrapper.js:96:44)
      at mount (.../x-react-calendar/node_modules/enzyme/build/mount.js:19:10)
      at Object.it (.../x-react-calendar/test/simple_test.js:16:39)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (.../x-react-calendar/internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.526s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Of course I had a look at link provided by the error message but I cannot find where to put the following piece (as described):

```js
// setup file
var enzyme = require('enzyme');
var Adapter = require('enzyme-adapter-react-16');

enzyme.configure({ adapter: new Adapter() });
```

Any idea what I am missing?

**Comment by eliperelman** [comment]
Hello @zeropaper! Since you are using Jest, you should be able to place the file in a `test_setup.js` file, then configure Jest to use this file for setup prior to testing:

```js
module.exports = {
  use: [
    // ...
    ['neutrino-preset-jest', {
      setupTestFrameworkScriptFile: '<rootDir>/test-setup.js'
    }]
  ]
};
```

Give that a shot and let me know.

**Comment by zeropaper** [comment]
Works like a charm!
Thank you so much @eliperelman !

**Comment by edmorley** [comment]
Perhaps this is worth adding as another example thing to customise? Here:
https://neutrino.js.org/presets/neutrino-preset-jest/#preset-options

@zeropaper, I don't suppose you'd be up for such a PR? :-)

The files that would need editing (due to the duplication from the way docs/packaging is set up) are:
https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-jest/README.md
https://github.com/mozilla-neutrino/neutrino-dev/blob/master/docs/presets/neutrino-preset-jest/README.md

**Comment by zeropaper** [comment]
@eliperelman I might have some time in the next days and I would be glad to do it. :)
