### ISSUE TITLE
Cannot understand why a setup with react + eslint + airbnb has linting issues

### ISSUE THREAD

**Issue by iongion** [mozilla-neutrino/neutrino-dev#364]
I use Visual Studio Code as my IDE, eslint is installed globally, and the IDE is set-up to perform linting using eslint, with the following project structure:

*package.json*:
```
{
  "name": "dog-editor-ng",
  "version": "1.0.0",
  "main": "src/index.jsx",
  "license": "MIT",
  "devDependencies": {
    "neutrino": "^7.1.10",
    "neutrino-middleware-eslint": "^7.1.10",
    "neutrino-preset-airbnb-base": "^7.1.10",
    "neutrino-preset-react": "^7.1.10"
  },
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build",
    "lint": "neutrino lint"
  },
  "dependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-hot-loader": "^3.0.0"
  }
}
```

*.neutrinorc.js*
```
module.exports = {
  use: [
    'neutrino-preset-react',
    'neutrino-preset-airbnb-base',
  ],
};
```

*.eslintrc.js*
```
// .eslintrc.js
const { Neutrino } = require('neutrino');
const api = Neutrino();
module.exports = api.call('eslintrc', [
  ['neutrino-middleware-eslint', {
    eslint: {
      rules: { semi: 'off' }
    }
  }],
  'neutrino-preset-react'
]);
```

*src/index.jsx*
```
import React from 'react';
import { render } from 'react-dom';
import { AppContainer } from 'react-hot-loader';
import Application from './Application';

const load = () => render((
  <AppContainer>
    <Application />
  </AppContainer>
), document.getElementById('root'));

if (module.hot) {
  module.hot.accept('./Application', load);
}

load();
```

*src/Application.jsx*
```
import React from 'react';
const Application = () => {
  return (
    <div>
      The application 1
    </div>
  );
};
export default Application;
```

IDE specific:

*.vscode/settings.json*
```
{
  "tslint.enable": false,
  "jshint.enable": false,
  "eslint.enable": true
}
```
*jsconfig.json*
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=759670
  // for the documentation about the jsconfig.json format
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules",
    "bower_components",
    "jspm_packages",
    "tmp",
    "temp",
    "build",
    "coverage"
  ],
  "include": [
    "src/**/*"
  ]
}
```

No matter what I do, running `npm run lint` gives this output:
```
...\dog-editor-ng\src\Application.jsx
  1:8   error  'React' is defined but never used                  no-unused-vars
  3:27  error  Unexpected block statement surrounding arrow body  arrow-body-style
...\dog-editor-ng\src\index.jsx
   1:8   error  'React' is defined but never used                 no-unused-vars
   3:10  error  'AppContainer' is defined but never used          no-unused-vars
   4:8   error  'Application' is defined but never used           no-unused-vars
   4:25  error  Unable to resolve path to module './Application'  import/no-unresolved
   4:25  error  Missing file extension for "./Application"        import/extensions
   6:26  error  Expected a newline after '('                      function-paren-newline
  10:4   error  'document' is not defined                         no-undef
  10:35  error  Expected a newline before ')'                     function-paren-newline
```

As if the linter ingores all rules.
I have attached a zip with the entire project too: 
[dog-editor-ng.zip](https://github.com/mozilla-neutrino/neutrino-dev/files/1397831/dog-editor-ng.zip)

**Comment by iongion** [comment]
The solution mentioned here https://github.com/mozilla-neutrino/neutrino-dev/issues/273 does not work, I cannot switch to  `neutrino-preset-airbnb` because this one is too old, webpack is not supported
As the person mentioned there, we try to use neutrino to avoid these kind of problems, I just followed the tutorial and it took me into this situation.

**Comment by eliperelman** [comment]
I'm investigating this, as I can replicate locally. Not sure why yet, but I'll take a look.

**Comment by eliperelman** [comment]
Looks like the major stopping point is that you aren't using the `react:recommended` settings with your lint configuration, which is the selling point of using `neutrino-preset-airbnb`. I'll see if we can get movement on the relevant PR.

**Comment by eliperelman** [comment]
https://github.com/mozilla-neutrino/neutrino-dev/issues/364

**Comment by eliperelman** [comment]
I think the airbnb preset has been released, would you give that a try?

**Comment by edmorley** [comment]
I guess this is another reason to resolve #352 some way.. :-)

**Comment by iongion** [comment]
@eliperelman did the changes, but now there is one issue left, apparently it does not detect the proper env:
```
[eslint] 'document' is not defined. (no-undef)
```
And this, even if I have forced the `.eslintrc.js` with:
```
...
...
    eslint: {
      env: {
        es6: true,
        browser: true,
        node: true,
      },
      globals: {
        document: true
      },
    },
...
...
```

The `package.json` became:
```
{
  "name": "dog-editor-ng",
  "version": "1.0.0",
  "main": "src/index.jsx",
  "license": "MIT",
  "devDependencies": {
    "neutrino": "^7.1.10",
    "neutrino-middleware-eslint": "^7.1.10",
    "neutrino-preset-airbnb": "^4.0.0",
    "neutrino-preset-node": "^7.2.1",
    "neutrino-preset-react": "^7.2.1"
  },
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build",
    "lint": "neutrino lint"
  },
  "dependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-hot-loader": "^3.0.0"
  }
}
```

With `.neutrinorc.js` set to:
```
module.exports = {
  use: [
    // 'neutrino-preset-node',
    // 'neutrino-preset-react',
    'neutrino-preset-airbnb',
  ],
};
```

With `.eslintrc.js` set to:
```
// .eslintrc.js
const { Neutrino } = require('neutrino');
const api = Neutrino();

module.exports = api.call('eslintrc', [
  ['neutrino-middleware-eslint', {
    eslint: {
      envs: ['es6', 'browser', 'node'],
      globals: {
        document: true
      },
    },
  }],
  // 'neutrino-preset-node',
  // 'neutrino-preset-react',
  'neutrino-preset-airbnb'
]);
```

Now, to do react development, does one need to use all of them together(I saw it here https://github.com/mozilla-neutrino/neutrino-dev/issues/273 - it is mentioned something about exclusivity ) ? are they exclusive/conflicting in any way ?
- neutrino-preset-node
- neutrino-preset-react
- neutrino-preset-airbnb

I have re-attached the entire project with changes applied for your convenience:
[dog-editor-ng.zip](https://github.com/mozilla-neutrino/neutrino-dev/files/1403965/dog-editor-ng.zip)

Anything else I can do ?

**Comment by iongion** [comment]
I just realized, with the updated airbnb, I still get the build error `npm run build`:
```× Building project failed
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration misses the property 'entry'.
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
    at ChainAction.validator.chain.errors [as mapper] (W:\Workspace\dog-editor-ng\node_modules\neutrino\src\webpack.js:49:20)
    at ChainAction.resolved (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:713:83)
    at resolved (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:175:19)
    at Future$1._fork (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:572:3)
    at drain (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:232:25)
    at settle (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:161:17)
    at resolved (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:175:5)
    at Immediate.EncaseP2$res (W:\Workspace\dog-editor-ng\node_modules\fluture\index.js:1764:7)
    at runCallback (timers.js:674:20)
    at tryOnImmediate (timers.js:645:5)
```

**Comment by eliperelman** [comment]
@iongion the Airbnb preset only controls how your project is linted, you still need a build preset, as noted on the docs for the Airbnb preset:

> You will also be using another Neutrino preset for building your application source code.

So in your `.neutrinorc.js`, put your airbnb preset and then your react preset:

```js
module.exports = {
  use: [
    'neutrino-preset-airbnb',
    'neutrino-preset-react'
  ]
};
```

**Comment by eliperelman** [comment]
Also, you won't be using a node preset with a react preset, since the node preset is for building Node.js applications, and the react preset is for building web applications.

**Comment by iongion** [comment]
Finally, it works, just removed almost everything from `.eslintrc.js`:

```
// .eslintrc.js
const { Neutrino } = require('neutrino');
const api = Neutrino();
module.exports = api.call('eslintrc', [
  'neutrino-preset-airbnb',
  'neutrino-preset-react'
]);
```

and 

// .neuntrinorc.js
```
module.exports = {
  use: [
    'neutrino-preset-airbnb',
    ['neutrino-preset-react', {
      html: {
        title: 'Enterprise 2.0'
      }
    }],
  ],
};
```

plus an awesome `package.json`
```
{
  "name": "dog-editor-ng",
  "version": "1.0.0",
  "main": "src/index.jsx",
  "license": "MIT",
  "devDependencies": {
    "neutrino": "^7.2.1",
    "neutrino-preset-airbnb": "^4.0.0",
    "neutrino-preset-react": "^7.2.1"
  },
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build",
    "lint": "neutrino lint"
  },
  "dependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-hot-loader": "next"
  }
}
```

The full project:
[dog-editor-ng.zip](https://github.com/mozilla-neutrino/neutrino-dev/files/1404816/dog-editor-ng.zip)

It works, it lints the same in the IDE and from the linter task itself, the React/Browser idioms are also properly recognized!

This is great! You can close the issue, thank you so much for the commitment and exhaustive help!

**Comment by eliperelman** [comment]
My pleasure! If you want to shorted up your `.eslintrc.js` file more, If you  don't pass an array to the `.call` method, it will use the same middleware as your `.neutrinorc.js` file:

```js
const { Neutrino } = require('neutrino');
const api = Neutrino();
module.exports = api.call('eslintrc');
```

Good luck with your project!
