### ISSUE TITLE
Jest testing throws an exception when config doesn't have Babel

### ISSUE THREAD

**Issue by constgen** [mozilla-neutrino/neutrino-dev#374]
Test suite: https://mega.nz/#!HdMnVbRI!3s6VchrK3EFxzsUTF-DUVb5G5PvW4SGNYzepzI7gLCs

I created a very simple preset for building an UMD library bundle. Building works correctly. But testing with `neutrino-preset-jest` thrown an exception:

```
> neutrino test

/Users/owner/Desktop/preset-umd/node_modules/deepmerge/dist/umd.js:63
        if (!isMergeableObject(source[key]) || !target[key]) {
                                                      ^

TypeError: Cannot read property 'env' of undefined
    at /Users/owner/Desktop/preset-umd/node_modules/deepmerge/dist/umd.js:63:55
    at Array.forEach (native)
    at mergeObject (/Users/owner/Desktop/preset-umd/node_modules/deepmerge/dist/umd.js:62:25)
    at deepmerge (/Users/owner/Desktop/preset-umd/node_modules/deepmerge/dist/umd.js:84:16)
    at config.module.rule.use.tap.opts (/Users/owner/Desktop/preset-umd/node_modules/neutrino-middleware-loader-merge/index.js:6:16)
    at tap (/Users/owner/Desktop/preset-umd/node_modules/webpack-chain/src/Use.js:12:18)
    at /Users/owner/Desktop/preset-umd/node_modules/neutrino-middleware-loader-merge/index.js:6:4
    at cond (/Users/owner/Desktop/preset-umd/node_modules/neutrino/src/api.js:105:28)
    at /Users/owner/Desktop/preset-umd/node_modules/ramda/src/cond.js:42:30
    at /Users/owner/Desktop/preset-umd/node_modules/ramda/src/internal/_arity.js:5:45
```

My assumption: this issue happens when there is no Babel in a Webpack config

**Comment by constgen** [comment]
You can see also other issues related to the same preset:
- https://github.com/mozilla-neutrino/neutrino-dev/issues/377
- https://github.com/mozilla-neutrino/neutrino-dev/issues/375
