### ISSUE TITLE
Not able change entry

### ISSUE THREAD

**Issue by lubo08** [mozilla-neutrino/neutrino-dev#468]
I would like to change for node js development index.js to server.js but I get error when I rename index.js to server.js 

/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:81
      var existsAt = compilation.assets[name].existsAt;
                                              ^

TypeError: Cannot read property 'existsAt' of undefined
    at StartServerPlugin.startServer (/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:81:47)
    at StartServerPlugin.afterEmit (/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:54:12)
    at Compiler.applyPluginsAsyncSeries1 (/home/lubo08/workspace/bimp/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/lubo08/workspace/bimp/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/home/lubo08/workspace/bimp/node_modules/webpack/lib/Compiler.js:354:15)
    at /home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:1050:13)
    at /home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:958:16
    at /home/lubo08/workspace/bimp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:137:15) 
neutrino config is 

module.exports = {
  options: {
    // Override to relative file, resolves to options.source + entry.*
    entry: 'server',
  },
  use: [
    'neutrino-preset-node',
    'neutrino-preset-airbnb-base'
  ]
};

**Comment by helfi92** [comment]
Is it possible that `compilation.assets[name]` is `undefined`?

**Comment by eliperelman** [comment]
I tracked this down, and it's a bug. Even though the option is named `entry`, when we create the webpack entry with `config.entry()`, we still use `index`, i.e. `config.entry('index')`. This causes the built file to still be `index.js`, while the start server plugin is looking for `server.js`.

**Comment by eliperelman** [comment]
Fixed with #469. Released in v7.3.3.

**Comment by edmorley** [comment]
For hotfixes in generally, what do you think is best: landing on master then backporting or vice versa? I know of projects that do it both ways, though have a slight preference to the former :-)

**Comment by eliperelman** [comment]
I would generally prefer landing on master first then backporting, but I opted for the other approach right now since the packages have completely diverged between master and release.

**Comment by lubo08** [comment]
Thanks a lot for so fast fix :) working right now.
