### ISSUE TITLE
neutrino-preset-jest produces error

### ISSUE THREAD

**Issue by dearfrankg** [mozilla-neutrino/neutrino-dev#56]
node v6.9.1
npm 4.3.0

Running the test

```
$npm test

> 2-nuetrino-react@0.1.0 test /Users/frankg/dev/code/temp/neutrino/2-nuetrino-react
> neutrino test

/Users/frankg/dev/code/temp/neutrino/2-nuetrino-react/node_modules/neutrino/src/neutrino.js:34
          throw exception;
          ^

TypeError: Neutrino was unable to load the module 'neutrino-preset-jest'. Ensure this module exports a function and is free from errors.
Cannot read property 'has' of undefined
    at module.exports.neutrino (/Users/frankg/dev/code/temp/neutrino/2-nuetrino-react/node_modules/neutrino-preset-jest/src/index.js:68:28)
    at Neutrino.presets.forEach.exception (/Users/frankg/dev/code/temp/neutrino/2-nuetrino-react/node_modules/neutrino/src/neutrino.js:26:35)
    at Array.forEach (native)
    at Neutrino (/Users/frankg/dev/code/temp/neutrino/2-nuetrino-react/node_modules/neutrino/src/neutrino.js:17:13)
    at run (/Users/frankg/dev/code/temp/neutrino/2-nuetrino-react/node_modules/neutrino/bin/neutrino:35:13)
    at Object.<anonymous> (/Users/frankg/dev/code/temp/neutrino/2-nuetrino-react/node_modules/neutrino/bin/neutrino:48:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.
```

/test/add.test.js

```
describe('sanity check', () => {
  it('can it be true', () => {
    expect(true).toBe(true)
  });
});
```

package.json

```
{
  "name": "2-nuetrino-react",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "config": {
    "presets": [
      "neutrino-preset-airbnb-base",
      "neutrino-preset-react",
      "neutrino-preset-jest"
    ]
  },
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build",
    "test": "neutrino test"
  },
  "keywords": [],
  "author": "Frank Gutierrez",
  "license": "MIT",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "neutrino": "^4.2.0",
    "neutrino-preset-airbnb-base": "^4.2.0",
    "neutrino-preset-jest": "^4.2.0",
    "neutrino-preset-react": "^4.2.0"
  }
}
```

**Comment by eliperelman** [comment]
Looks like there was a syntax error in a recent PR. My apologies for letting that slip in. This should now be fixed in the Jest preset 4.2.1. Thanks!
