### ISSUE TITLE
Create project with Vue + StandardJS rules, module build failed

### ISSUE THREAD

**Issue by jackysee** [mozilla-neutrino/neutrino-dev#600]
run `yarn create @neutrinojs/project vueapp2` with these answers

- A web or Node.js application
- Vue
- Karma
- StandardJS rules

The module build is failed when starting the app.
```
C:\workspace\web\neutrino-test\> cd vueapp2
C:\workspace\web\neutrino-test\vueapp2> yarn start
yarn run v1.1.0
$ neutrino start
√ Development server running on: http://localhost:5000
√ Build completed

ERROR in ./src/index.js
Module build failed: Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from:
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Plugins.load (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\plugins.js:106:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\plugins.js:146:21)
    at loadFromDisk (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\config-file.js:492:35)
    at load (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\config-file.js:550:20)
    at configExtends.reduceRight (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\config-file.js:403:28)
    at Object.loadObject (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config\config-file.js:529:35)
    at new Config (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\config.js:72:46)
    at new CLIEngine (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint\lib\cli-engine.js:420:23)
    at Object.module.exports (C:\workspace\web\neutrino-test\vueapp2\node_modules\eslint-loader\index.js:176:27)
 @ multi (webpack)-dev-server/client?http://localhost:5000 (webpack)/hot/dev-server.js ./src/index
```

It will be passed if I comment the `@neutrinojs/standardjs` entry in the `.neutrinorc.js`.

**Comment by eliperelman** [comment]
This should now be fixed in v8.0.12. Please give it a shot and re-open if you notice this didn't work as expected. Thanks!

**Comment by c835722** [comment]
Failed for me with v8.0.13 with same exception signature above.
Node, Jest, Standard options on npx @neutrinojs/create-project kata33-neutrinoV8.
yarn build or yarn lint to reproduce.

**Comment by c835722** [comment]
@eliperelman can we reopen this issue?

**Comment by jackysee** [comment]
Personal test on 8.0.13 the build error is fixed.
But a linting problem remains, which should be fixable by `yarn lint --fix`.

**Comment by c835722** [comment]
>yarn lint --fix does **not** resolve the issue for me.

Just updating my neutrino project instantiation from the previous comment as the following:
>npx @ neutrinojs/create-project kata33-neutrinoV8
