### ISSUE TITLE
cannot change server entry 

### ISSUE THREAD

**Issue by lubo08** [mozilla-neutrino/neutrino-dev#660]
I would like to change for node js development index.js to server.js but I get error when I rename index.js to server.js

/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:81
var existsAt = compilation.assets[name].existsAt;
^

TypeError: Cannot read property 'existsAt' of undefined
at StartServerPlugin.startServer (/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:81:47)
at StartServerPlugin.afterEmit (/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:54:12)
at Compiler.applyPluginsAsyncSeries1 (/home/lubo08/workspace/bimp/node_modules/tapable/lib/Tapable.js:222:13)
at Compiler.afterEmit (/home/lubo08/workspace/bimp/node_modules/webpack/lib/Compiler.js:365:9)
at require.forEach.err (/home/lubo08/workspace/bimp/node_modules/webpack/lib/Compiler.js:354:15)
at /home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:473:16
at iteratorCallback (/home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:1050:13)
at /home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:958:16
at /home/lubo08/workspace/bimp/node_modules/graceful-fs/graceful-fs.js:43:10
at FSReqWrap.oncomplete (fs.js:137:15)
neutrino config is

module.exports = {
  use: [
    '@neutrinojs/node',
    '@neutrinojs/standardjs'
  ],
  options: {
    mains: {
      index: 'server'
    }
  }
};

was fixed for version 7 looks like not fixed in version 8?

**Comment by eliperelman** [comment]
Changing the `mains` option is tricky with Node.js because the start-server middleware creates a server using the **built** file in order to start the server, which in your case the mapping is `server.js` -> `index.js`.

The easiest solution here is just to keep the names the same in options if you want to change the file name:

```js
module.exports = {
  options: {
    mains: {
      server: 'server'
    }
  },
  use: [
    '@neutrinojs/node'
  ]
};
```
