### ISSUE TITLE
neutrino lint --fix > TypeError: neutrino.regexFromExtensions is not a function

### ISSUE THREAD

**Issue by lubo08** [mozilla-neutrino/neutrino-dev#664]
note able use this command.

$ neutrino lint --fix
× Running lint failed
TypeError: neutrino.regexFromExtensions is not a function
    at module.exports (C:\Data\SVD_Work\Projects\BI_Monitoring_2\node_modules\@neutrinojs\compile-loader\index.js:6:36)
    at cond (C:\Data\node\node_modules\neutrino\src\api.js:105:28)
    at C:\Data\node\node_modules\neutrino\node_modules\ramda\src\cond.js:42:30
    at C:\Data\node\node_modules\neutrino\node_modules\ramda\src\internal\_arity.js:5:45
    at Object.use (C:\Data\node\node_modules\neutrino\src\api.js:152:7)
    at module.exports (C:\Data\SVD_Work\Projects\BI_Monitoring_2\node_modules\@neutrinojs\node\index.js:47:12)
    at cond (C:\Data\node\node_modules\neutrino\src\api.js:105:28)
    at C:\Data\node\node_modules\neutrino\node_modules\ramda\src\cond.js:42:30
    at C:\Data\node\node_modules\neutrino\node_modules\ramda\src\internal\_arity.js:5:45
    at Object.use (C:\Data\node\node_modules\neutrino\src\api.js:152:7)
    at cond (C:\Data\node\node_modules\neutrino\src\api.js:109:30)
    at C:\Data\node\node_modules\neutrino\node_modules\ramda\src\cond.js:42:30
    at C:\Data\node\node_modules\neutrino\node_modules\ramda\src\internal\_arity.js:5:45
    at use (C:\Data\node\node_modules\neutrino\src\api.js:152:7)
    at _map (C:\Data\node\node_modules\neutrino\node_modules\ramda\src\internal\_map.js:6:19)
    at map (C:\Data\node\node_modules\neutrino\node_modules\ramda\src\map.js:57:14)

package:
"devDependencies": {
    "@neutrinojs/airbnb-base": "^8.0.15",
    "@neutrinojs/node": "^8.0.15",
    "neutrino": "^8.0.15"
  },
  "dependencies": {
    "express": "^4.15.3",
    "yaml-config": "^0.3.0"
  }

neutrino:
module.exports = {
  options: {
    mains: {
      server: 'server'
    }
  },
  use: [
    '@neutrinojs/node',
    '@neutrinojs/airbnb-base'
  ]
};

**Comment by eliperelman** [comment]
Hmm, I don't seem to replicate here. Could you provide a minimal test repo to try this out on?

**Comment by eliperelman** [comment]
cc @lubo08

**Comment by zeropaper** [comment]
Actually, it seems that I can replicate that when I want to make a commit (for a PR):
```sh
added 250 packages in 13.111s
/home/vale/.nvm/versions/node/v9.2.1/lib/node_modules/@neutrinojs/env -> /home/vale/repos/neutrino-dev/packages/env
husky > npm run -s precommit (node v9.2.1)

 ❯ Running tasks for *.js
   ✖ yarn lint --fix
     → error Command failed with exit code 1.
     git add
✖ yarn lint --fix found some errors. Please fix them and try committing again.
yarn run v1.3.2
$ node packages/neutrino/bin/neutrino lint --fix /home/vale/repos/neutrino-dev/packages/env/index.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

          module.js:544
throw err;
^

Error: Cannot find module 'ramda'
at Function.Module._resolveFilename (module.js:542:15)
at Function.Module._load (module.js:472:25)
at Module.require (module.js:585:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/vale/repos/neutrino-dev/packages/neutrino/bin/neutrino.js:10:5)
at Module._compile (module.js:641:30)
at Object.Module._extensions..js (module.js:652:10)
at Module.load (module.js:560:32)
at tryModuleLoad (module.js:503:12)
at Function.Module._load (module.js:495:3)
error Command failed with exit code 1.

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by edmorley** [comment]
Has anyone seen this recently?

**Comment by edmorley** [comment]
Closing this for now - but please comment if it occurs again :-)
