### ISSUE TITLE
Improve error message when using .tap() on undefined plugin

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#687]
**STR:**
1. `yarn add neutrino@8.0.18 @neutrinojs/web@8.0.18`
2. `mkdir src`
3. `touch contribute.json src/index.js`
4. Create a `.neutrinorc.js` containing:
```js
module.exports = {
  use: [
    '@neutrinojs/web',
    (neutrino) => {
      neutrino.config
        .plugin('copy')
        .tap(args => {
          args[0] = [
            'contribute.json'
          ];
          return args;
        });
    }
  ]
}
```
5. `yarn start`

**Expected:**
Error message that makes the mistake clear. eg:
`Error: Plugin 'copy' is not defined`
(along with a stack trace that points to the correct line in `.neutrinorc.js`)

**Actual:**
webpack-chain gives an error message that is hard to track back to a root cause (unclear error message and does not reference a specific line in `.neutrinorc.js`):
```
C:\Users\Ed\src\neutrino-test\node_modules\webpack-chain\src\Plugin.js:9
    this.init((Plugin, args = []) => new Plugin(...args));
                                     ^

TypeError: Plugin is not a constructor
    at init (C:\Users\Ed\src\neutrino-test\node_modules\webpack-chain\src\Plugin.js:9:38)
    at Object.toConfig (C:\Users\Ed\src\neutrino-test\node_modules\webpack-chain\src\Plugin.js:38:12)
    at clean.Object.assign.plugins.plugins.values.map.plugin (C:\Users\Ed\src\neutrino-test\node_modules\webpack-chain\src\Config.js:69:59)
    at Array.map (<anonymous>)
    at module.exports.toConfig (C:\Users\Ed\src\neutrino-test\node_modules\webpack-chain\src\Config.js:69:38)
    at ChainAction.Future.chain.chain.chain [as mapper] (C:\Users\Ed\src\neutrino-test\node_modules\neutrino\src\api.js:281:61)
    at ChainAction$resolved [as resolved] (C:\Users\Ed\src\neutrino-test\node_modules\fluture\index.js:805:27)
    at resolved (C:\Users\Ed\src\neutrino-test\node_modules\fluture\index.js:220:19)
    at Immediate.EncaseP2$res [as _onImmediate] (C:\Users\Ed\src\neutrino-test\node_modules\fluture\index.js:1847:7)
    at runCallback (timers.js:791:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

The root cause here is that the `copy` plugin is only defined when `command === 'build'`, and so there is no such plugin to `.tap()` during yarn start.

**Comment by eliperelman** [comment]
I could definitely see how this would be an issue. Technically this issue can arise from not using `tap` at all:

```js
neutrino.config.plugin('copy');
```

This is due to the way the `.plugin` method works:

https://github.com/mozilla-neutrino/webpack-chain/blob/2445476d0d7f444c34060f383c890597ca0d2e8d/src/Config.js#L51-L57

Using these methods creates an entry with that name, and then expects it to be defined. Obviously in the case of conditional plugins, this creates a problem. We do specifically state in the docs about the conditional nature of the plugins:

https://neutrino.js.org/packages/web/#plugins

> _Note: Some plugins are only available in certain environments. To override them, they should be modified conditionally._

But I agree the error messaging could be better in this scenario. This would have to be done in webpack-chain.

**Comment by edmorley** [comment]
Yeah I agree this is not expected to work - it's the clearer error message that this issue is about :-)
