### ISSUE TITLE
Error when scaffolding with create-project after linting style selection

### ISSUE THREAD

**Issue by spadesr** [mozilla-neutrino/neutrino-dev#764]
Hey guys. I'm trying to scaffold a library project. When I use the create-project tool, I get an error at `create x/package.json`. 

### Scenarios

This happens when I:
- Use npx
- Use Yarn
- Select Standard JS for linting
- Select Airbnb for linting

It doesn't happen when I:
- Select 'none' for linting.

### Steps I've tried to fix it

- Do install on both LTS and latest production release of Node.
- Uninstall and reinstall node_modules.
- Use globally and locally installed Neutrino.
- Reinstall Yarn.

### My system 

- Ubuntu Linux 17.10 using nvm to manage Node installations.

### Thrown error messages

When using npm:
```
? 🤔  First up, what would you like to create? A library
? 🤔  Next, what kind of library would you like to create? Web and/or Node.js
? 🤔  Would you like to add a test runner to your project? Jest
? 🤔  Would you like to add linting to your project? Airbnb style rules

👌  Looks like I have all the info I need. Give me a moment while I create your project!

   create ramsta/package.json
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/commands/init/templates/airbnb-base/**
    at EditionInterface.exports.copy (/home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (/home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at templates.forEach.template (/home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/commands/init/index.js:128:15)
    at Array.forEach (<anonymous>)
    at Project.writing (/home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/commands/init/index.js:125:15)
    at Object.<anonymous> (/home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/rishi/.npm/_npx/26401/lib/node_modules/@neutrinojs/create-project/node_modules/yeoman-generator/lib/index.js:400:11)
```
When using Yarn:
```
? 🤔  First up, what would you like to create? A library
? 🤔  Next, what kind of library would you like to create? Web and/or Node.js
? 🤔  Would you like to add a test runner to your project? Jest
? 🤔  Would you like to add linting to your project? StandardJS rules

👌  Looks like I have all the info I need. Give me a moment while I create your project!

   create ramsta/package.json
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/rishi/.config/yarn/global/node_modules/@neutrinojs/create-project/commands/init/templates/standardjs/**
    at EditionInterface.exports.copy (/home/rishi/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (/home/rishi/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at templates.forEach.template (/home/rishi/.config/yarn/global/node_modules/@neutrinojs/create-project/commands/init/index.js:128:15)
    at Array.forEach (<anonymous>)
    at Project.writing (/home/rishi/.config/yarn/global/node_modules/@neutrinojs/create-project/commands/init/index.js:125:15)
    at Object.<anonymous> (/home/rishi/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/rishi/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/rishi/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/rishi/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:400:11)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: /home/rishi/.yarn/bin/create-project
Arguments: ramsta
Directory: /home/rishi/code
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/rishi/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by jonas-e-medicus** [comment]
Same issue
OS: osx
node: v9.7.1
yarn: 1.5.1
npm: 5.6.0

command: $ yarn create @neutrinojs/project regraph

**Comment by eliperelman** [comment]
I couldn't replicate, but was running into strange permission errors when trying to manually download and extract the package tarball. @spadesr @jonas-e-medicus could you both try the latest version, v8.2.1, and see if this is still an issue?

@edmorley I'm wondering if there was a file ownership issue on this last publish. When I open v8.2.0 using `sudo su`, there were no dotfiles (e.g. `.eslintrc`) in the linting directories, hence the problems above. I didn't have any permissions issues extracting the tarballs of v8.1.0 or the newly-published v8.2.1.

**Comment by spadesr** [comment]
I just tried it, and it creates the project just fine on v8.2.1! Verified it with both Standard and Airbnb. Good stuff @eliperelman! Thank you.

**Comment by eliperelman** [comment]
Great, thank you so much for your patience!
