### ISSUE TITLE
Build failed on empty react project

### ISSUE THREAD

**Issue by emzero** [mozilla-neutrino/neutrino-dev#782]
### Bug

Please try to answer the following questions:

- What version of Neutrino are you using?
Latest one using `yarn create @neutrinojs/project`

- Are you using the Yarn client or the npm client? What version?
Yarn 1.5.1

- What version of Node.js are you using?
Node 8.9.3

- What operating system are you using?
Windows 7 x64

- What did you do?
```
yarn create @neutrinojs/project neutrino-react
```
All defaults chosen (first option), then:
```
cd neutrino-react
yarn build
```

- What did you expect to happen?
Successful build

- What actually happened, contrary to your expectations?
The following error:
```
Welcome to Neutrino! �
To help you create your new project, I am going to ask you a few questions.

? �  First up, what would you like to create? A web or Node.js application
? �  Next, what kind of application would you like to create? React
? �  Would you like to add a test runner to your project? Jest
? �  Would you like to add linting to your project? Airbnb style rules

�  Looks like I have all the info I need. Give me a moment while I create your project!

   create neutrino-react\package.json
   create neutrino-react\.neutrinorc.js
   create neutrino-react\src\App.css
   create neutrino-react\src\App.jsx
   create neutrino-react\src\index.jsx
   create neutrino-react\test\simple_test.js
   create neutrino-react\.eslintrc.js

⏳  Installing dependencies: prop-types, react, react-dom, react-hot-loader
⏳  Installing devDependencies: @neutrinojs/react, neutrino, @neutrinojs/jest, @neutrinojs/airbnb
⏳  Performing one-time lint

Hooray, I successfully created your project!

I have added a few yarn scripts to help you get started:
  • To build your project run:  yarn build
  • To start your project locally run:  yarn start
  • To execute tests run:  yarn test
  • To lint your project manually run:  yarn lint
    You can also fix some linting problems with:  yarn lint --fix

Now change your directory to the following to get started:
  cd neutrino-react

❤️  Neutrino
Done in 375.07s.

D:\Desktop\react
λ cd neutrino-react\

D:\Desktop\react\neutrino-react  (neutrino-react@1.0.0)
λ yarn build
yarn run v1.5.1
$ neutrino build
× Building project failed
./src/index.jsx
Module build failed: Module failed because of a eslint error.
error: Expected a newline after '(' (function-paren-newline) at src\index.jsx:6:26:
  4 |
  5 | const root = document.getElementById('root');
> 6 | const load = () => render((
    |                          ^
  7 |   <AppContainer>
  8 |     <App />
  9 |   </AppContainer>


error: Expected a newline before ')' (function-paren-newline) at src\index.jsx:10:8:
   8 |     <App />
   9 |   </AppContainer>
> 10 | ), root);
     |        ^
  11 |
  12 | // This is needed for Hot Module Replacement
  13 | if (module.hot) {


2 errors found.
2 errors potentially fixable with the `--fix` option.
 @ multi ./src/index
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c neutrino build
Directory: D:\\Desktop\\react\
eutrino-react
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Desktop\\react\
eutrino-react\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Doing `yarn lint --fix` and then `yarn build` again doesn't solve the problem. It fails with another error:
```
Module build failed: Error: Cannot find module '@babel/helper-module-imports'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (D:\Desktop\react\neutrino-react\node_modules\fast-async\plugin.js:10:25)
    at Function.memoisePluginContainer (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
    at Function.normalisePlugin (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
    at D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\Desktop\react\neutrino-react\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\Desktop\react\neutrino-react\node_modules\babel-loader\lib\index.js:50:20)
 @ multi ./src/index
error An unexpected error occurred: "Command failed.
Exit code: 1
```

**Comment by edmorley** [comment]
Hi! Sorry for the delayed reply.

There are two issues above. The first (there being lint errors in the template project) will be fixed by #.

The second was due to a regression in a dependency we use:
https://github.com/MatAtBread/fast-async/issues/53

...which is fixed in the latest version of fast-async (and also a workaround added to neutrino v8.2.2). If you remove your `node_modules` and `yarn.lock` and reinstall, you should pick up the fixed versions :-)
